Artsdatabanken/Assessments

- Assessments.Frontend.Web/Controllers/TestController.cs
- Assessments.Frontend.Web/Infrastructure/AssessmentApiService.cs
- Assessments.Frontend.Web/Models/RL2021ViewModel.cs
- Assessments.Frontend.Web/Views/Home/Index.cshtml
- Assessments.Frontend.Web/Views/Test/Index.cshtml
- Assessments.Frontend.Web/Views/Test/List2021.cshtml
- Assessments.Frontend.Web/Views/Test/SpeciesAssessment2021.cshtml
- Assessments.Frontend.Web/wwwroot/css/site.css
- Assessments.Frontend.Web/wwwroot/js/site.js
- Fisket litt på stilene til søkeformen slik at den ligner forsidesøket på adb forsiden. Når vi er fornøyd med den bør det flyttes over som element man kan dytte rett inn i prosjektet grafisk profil, og bare gjenbrukes her.
- La till 2021 listevisning
- La til 2021 detaljvisning (lite innhold ennå)
- Endret listevisning fra tabell til liste, slik at den lett kan endres til grid-visning
- La til en rask javascript-knapp for å endre mellom visningsmodus. Optimalt sett burde det kanskje vært lenker som legger på en url parameter, slik at man ikke "mister" visningstypen om man søker eller filtrerer? 
Ved å bytte ut tabell med liste på denne måten er det lettere å ha kontroll på forskjellige skjermstørrelser i tillegg til at det er lett å endre visningsmodus. Jeg tenker vi lager ferdig …
> 2021 Landingssider, listevisning og gridvisning

- Assessments.Frontend.Web/Controllers/RedlistController.cs
- Assessments.Frontend.Web/Models/RL2021ViewModel.cs
- Assessments.Frontend.Web/Views/Redlist/List/partials/_Graphs.cshtml
- Assessments.Frontend.Web/Views/Shared/_Category.cshtml
- Assessments.Frontend.Web/wwwroot/json/categories.json
Add Region Graph & Stats.  
-> added inline text about the graph, as we want better filtering first.
Fixed Criteria. 
-> Bug was the filter. The filter removed more than 1000 relevant matches. 
Fixed crash due to counting nonexisting items on narrow searches.
-> when the dictionary is empty it did not count to zero, but instead set null for max comparisons. Now it does.
Fixed crash for elements without category
-> category matcher now supports null and empty string
> Add Region Graph & Stats. Fix Criteria. Fix crash due to counting nonexisting items on narrow searches.

- Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Fylkesforekomster.cshtml
- Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Historikk.cshtml
- Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_SpeciesInfo.cshtml
- Assessments.Frontend.Web/Views/Redlist/List/partials/_ListView.cshtml
- Assessments.Frontend.Web/Views/Shared/_Byline.cshtml
- Assessments.Mapping/Helpers/SpeciesAssessment2021ProfileHelper.cs
- Assessments.Mapping/Models/Species/SpeciesAssessment2021.cs
- Assessments.Mapping/SpeciesAssessment2021Profile.cs
har endret logikk for "ExpertCommittee" - det er nå det samme originale navnet som er lagret i databasen for rødlista, men uten vurderingsområde (norge/svalbard)
la til "SpeciesGroup" - som heller ikke har vurderingsområde, men har logikk for splitting av navn (hentet fra rødlisteprosjektet og som tidligere ble brukt på "ExpertCommittee" feltet)
oppgaven ble beskrevet og diskutert i to ulike issues, beholder og holder tråden i denne https://github.com/Artsdatabanken/assessments-frontend/issues/90
> Add species group and modify expertcommittee name (#90)

- Assessments.Frontend.Web/wwwroot/css/site.css
Previously it was just hidden on smaller sizes.
Now it is availiable on top, but not in an optimal way.
Breadcrumbs hidden on the same size due to overlapping content.
> menu is now availiable on smaller sizes, although not optimal

- Assessments.Frontend.Web/Infrastructure/Extensions.cs
- Assessments.Frontend.Web/Infrastructure/Helpers.cs
- Assessments.Frontend.Web/Infrastructure/Services/ExpertCommitteeMemberService.cs
- Assessments.Frontend.Web/Startup.cs
- Assessments.Frontend.Web/Views/Redlist/Assessment/SpeciesAssessment2021.cshtml
- Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_ExpertCommitteeMembers.cshtml
tjeneste som kobler ekspertgruppemedlemmer (i en csv fil - konvertert fra excel) med en vurdering
brukes til "Siden siteres som" - midlertidig lagt til nederst på vurderingssiden (uten styling):
https://github.com/Artsdatabanken/assessments-frontend/blob/89e0b6ce89141e5a86d3550400fe6e41d00f9903/Assessments.Frontend.Web/Views/Redlist/Assessment/SpeciesAssessment2021.cshtml#L43
html/styling endres i filen:
https://github.com/Artsdatabanken/assessments-frontend/blob/89e0b6ce89141e5a86d3550400fe6e41d00f9903/Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_ExpertCommitteeMembers.cshtml
> Add expert committee members (#72)

- Assessments.Frontend.Web/Views/Shared/_PageMenu.cshtml
- Assessments.Frontend.Web/wwwroot/css/graphs.css
- Assessments.Frontend.Web/wwwroot/css/site.css
similar to some other pages, menu gets placed on bottom on smaller screens.
disimmilar to the same pages, we do not include double hamburgers. 
For futher discussion on this topic make new issue.
> fixed menu based on request

- Assessments.Frontend.Web/Infrastructure/Helpers.cs
- Assessments.Frontend.Web/Views/Redlist/List/List2021.cshtml
beholder parametre på riktig måte når man går mellom sidene i listen (paginering)
nye filter/parametre må legges til manuelt nå (hadde kode som gjorde det automatisk, men ikke fungerte optimalt tidligere)
> Keep querystrings when paging

- Assessments.Frontend.Web/Views/Redlist/List/partials/_Graphs.cshtml
- Assessments.Frontend.Web/wwwroot/css/graphs.css
Habitat now has three main graph types, normal greyscale, normal colour and down.
- removed all down-text and code related to rotating text
Normal colour:
- added css-jump which made the graphs more narrow on smaller screens
- added table view size for super-tiny screens, but this one is triggered at very small size, as the one above allows quite small views
Down:
- Contained with a max width for the entire graph to avoid too large bars
- added tiny extra jump where the text optimizes size a bit
- added table view size for super-tiny screens
> Habitat -> Downgraph. Supertiny graphs are table form.

- Assessments.Frontend.Web/wwwroot/css/searchAndFilter.css
- Assessments.Frontend.Web/wwwroot/js/site.js
default for collapsed filters is now not checked. Thus url will not be full of IsCheck values "by default"
> reverse checked input to make url prettier

- Assessments.Frontend.Web/Infrastructure/Helpers.cs
Forkortelsen aff. i vitenskapelig navn er ikke lenger i kursiv. Dette gjelder 4 arter.
> aff. in scientific name not in italic

- Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_ListView.cshtml
- Assessments.Frontend.Web/wwwroot/css/search.css
- Assessments.Frontend.Web/wwwroot/json/glossary.json
Legger til en enkel tekst når det ikke finnes treff i rødlista. 
I issuen #87 er det også snakk om å gjøre mer enn dette, men dette er en start, og dette er noe vi absolutt må ha på plass.
> add text for no result in rødlista 2021

- Assessments.Frontend.Web/Infrastructure/Criteria.cs
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_CategoryDegrade.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_CategoryDescription.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Header.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Ingress.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/Shared/_PageMenu.cshtml
- Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
- Assessments.Frontend.Web/Views/Shared/_Category.cshtml
- Assessments.Frontend.Web/wwwroot/css/categorybar.css
- Assessments.Frontend.Web/wwwroot/css/rl2021.css
- Assessments.Frontend.Web/wwwroot/css/site.css
- Headerstyling har endret seg. Skal senere fikses i drupal også.
- Meny har fått klikkbar overskrift.
- Lenke i kategoriskalaen (som ikke går noe sted ennå...)
- fikset typo for bkriteriet ( fixes #369 )
- Svalbard har fått bli underoverskrift - men kun for svalbardarter. Vi har ikk Norge på Norge-arter. 
(God eksempelart på ingress for nedgradert: 31847)
**Endringer i ingress:**
- fjernet oneliner om rødlista
- for arter med criteriasummarized, la til overskriftene på relevante brukte kriterier
- for nedgraderte, la til setning om det 
- nedgradert har fått ankerlenke 
- trolig utdødd har blitt omplassert
> Endringer i into ++

- Assessments.Frontend.Web/Views/Redlist/Species/2021/List/List.cshtml
- Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
- Assessments.Frontend.Web/appsettings.Development.json
- Assessments.Frontend.Web/appsettings.json
la til google analytics sporingskode (production og staging), koblet mot eksisterende kontoer
gjeldende konto hentes fra appsettings
_usikker om det fungerer i staging miljø, vi har kanskje ikke satt opp riktig konfigurasjon for dette_
..også litt usikker på om dette fungerer ordentlig når sidene ligger på et subdomene (litt vanskelig å teste før vi bygger det ut på beta) 
la også til en (bedre) tittel på listesiden
> Add google analytics and modify list title (#454)

- Assessments.Frontend.Web/wwwroot/js/search.js
URL-en til autocomplete-forslagene benytter nå window.location.pathname istedet for en absolutt sti
> fix autocomplete url build-up

- Assessments.Transformation/Program.cs
fikser en feil ved transformering (med automapper) som førte til at ekspertgruppe ble feil
har allerede kjørt koden (som henter data fra databasen og laster opp nye filer) og sjekket at det ble riktig
> Adjust (automapper) transformation (fix #499)

- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Habitat.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_ImpactFactors.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_PopulationProportions.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_RegionStatistics.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Regions.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_SpeciesDetails.cshtml
- Assessments.Frontend.Web/wwwroot/css/assessment.css
- Assessments.Frontend.Web/wwwroot/css/search.css
- testart for noen som kategorimessig KAN ha habitat og påvirkningsfaktor men ikke har det oppgitt: 37916
- skjuler geografi for NA, NE, LC -> med mindre noen har oppgitt en region som ikke er "ingen". altså at noen har oppgitt en eller anna form for distribusjon. Forsøket her er egentlig å skjule alle uten distribusjon, men også alle på NA/NE fordi de potensielt kan være gamle rester.
- Habitatboksen skjules på NA,NE,LC,RE - med mindre den  er oppgitt der. da vises den. Forhåpentligvis.
- påvirkningsfaktorer bør virke likt som habitat.
- kriterier skal vel i teorien aldri vises med mindre kriteriene er brukt. Er det optimalt? Uvisst. Men det er nå så.
- Disse tre har nå fått interne overskrifter, som sikkert ikke er optimale,
- Disse endrer seg mellom summary og full visning.
- Detaljer …
> Logikk for skjuling/vising av innhold.

- Assessments.Frontend.Web/Controllers/HomeController.cs
- Assessments.Frontend.Web/Startup.cs
- Assessments.Frontend.Web/wwwroot/js/swagger.js
setter inn tittel på apiet via kode, som erstatter javascript
ignorerer homecontroller i api'et (lagt til for sitemap), slik at generering av json for swagger fungerer igjen
usikker på om tittel er ok ("Assessments api - Artsdatabanken"), men swagger fungerer bare lokalt i utviklingsmiljøet (#457)
swagger skal sikkert tas i bruk på et tidspunkt, vurdere om tittel skal endres da?
> Improve swagger title handling and fix swagger json 

- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Citation.cshtml
excelfilen med ekspertkomiteemedlemmene er oppdatert med ny rollle "Nestleder" (kun gjort på gruppen for karplanter)
har derfor lagt til rollene også i sorteringen (brukes til sitering på vurderinger), slik at rekkefølgen blir leder->nestleder->medlem - og så alfabetisk på etternavn
man må slette filen species-experts.csv i Cache mappen på webprosjektet for å se endringen lokalt (siden excelfilen brukt som kilde er oppdatert) - det skjer automatisk ved bygging til prod og test
fixes #521
> Add new role to expertcommittee member sorting (#521)

- .github/workflows/develop.yml
- .github/workflows/main.yml
- .github/workflows/test.yml
- README.md
Da har jeg tatt en liten razzia og gjort følgende:
Linux/Docker
Opprettet en ny workflow, develop, som er regnet som fritt vilt og alt av PR/push trykkes automatisk ut til: https://assessments-fe-dev.test.artsdatabanken.no. Den bører IKKE det som kjøres på beta.artsdatabanken.no. Så her er det bare å slå seg løs.
Har gjort endringer på workflow som het test.yml. Prøver her funksjonalitet jeg ikke har testa før, men om det virker så tror jeg det dekker behovet. Tanken er at denne kun bygges og publiseres ved PR som lukkes OG merges. Det skjer da automatisk og publiseres hit: https://assessments-fe.test.artsdatabanken.no
Har valgt å beholde main.yml selv om denne sannsynligvis er overflødig, siden den er driftsmessig gratis å ha kjørende. Her må man manuelt trigge publisering til server. …
> Build from dev

- Assessments.Frontend.Web/wwwroot/css/listview.css
- Assessments.Frontend.Web/wwwroot/json/speciesgroup.json
Fremfor å bruke mye tid på å endre svg'ene til å støttes også i chrome, ble det lagret en versjon i png for de to ikonene som ikke fungerte som er lastet opp på design.artsdatabanken.no sammen med resten av ikonene. Det ser ut som svg'ene bestod av element med data: bilde fremfor faktiske paths, som er grunnen til at det ble tull med img-taggen. 
I utgangspunktet hadde vi en visjon om å embedde svg'ene for å kunne justere farger på pathsene, hilights osv, men per nå ligger de uansett i et annet prosjekt så det toget er kjørt for et halvår siden. Så da kan de like godt være png.
> fixes #511 - swapped unloading svgs for pngs to do a quickfix

- Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Citation.cshtml
gjør om hardkodet url (som var feil) i listevisningen til å vise faktisk side man er på (uten url parametere)
url blir nå riktig i alle miljø og på alle domener (også om applikasjonen flyttes, eller url endres via f.eks routing)
> Fix citation url in list view

- Assessments.Mapping/SpeciesAssessment2021ExportProfile.cs
eksporten fjerner html tagger på feltet kriteriedokumentsjon, men metoden tok også bort endel gyldige tegn og tekst ("<", ">" og teksten som kom innenfor disse)
har oppdatert regex slik at teksten beholdes
> Remove html tags but keep valid text in export (#572)

- Assessments.Frontend.Web/wwwroot/js/search.js
fixes #564 
Mulig noen nettlesere slenger på en '/' bak window.location.pathname, mens andre ikke gjør det.. Det skal nå funke i begge tilfeller.
> fix bad link navigating to assessment

- Assessments.Frontend.Web/Infrastructure/Extensions.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
- Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Paginator.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Paginator.cshtml
la til utvidelse som hjelper å sette inn alle querystring parametere i lenkene for paginering - slik at man slipper å sette inn disse manuelt
- fjernet gammel kode med liste og paginering
- implementert i pagingering på rødlista også
> Add querystring extension, keep query parameters in pagers

- Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
- Assessments.Frontend.Web/Infrastructure/Categories.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
- Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_ListView.cshtml
- Assessments.Mapping/AlienSpecies/AlienSpeciesAssessment2023.cs
- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs
- Assessments.Shared/Helpers/Extensions.cs
gjøre om category til enum, close #657 
- category er nå gjort om til enum, endret datamodellen og la til mapping
- category inneholder navn (via en "displayname" attributt) og verdi (selve kategorien)
- la til utvidelse for å vise "displayname"
- erstattet hardkodet liste med kategorier med ny enum (mulig å legge til beskrivelse på enum også, men virket som den originale listen bare brukte beskrivelse i små bokstaver fra navn(!?)
- byttet fra alienspeciescategory (som var tatt i bruk for tidlig) til category i visning
alle vurderinger har nå category, la til en som heter "Undefined" for de som mangler
disse vises også i listen, vi kan velge å ta de bort når vi transformerer data fra databasen, eller la de ligge så lenge så man ser de (siden de faktisk er med slik det er i koden som …
> make category enum

- Assessments.Mapping/AlienSpecies/AlienSpeciesAssessment2023.cs
- Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs
La til felt for utslagsgivende kriterier og opprettet nye felt for skår på de to aksene i risikovurderingen: Invasjonspotensial og økologisk effekt. Closes #666.
Kriterier brukes på artssidene og i filtermenyen (#634)
Skårene brukes i filtre omtalt i #631.
* La til feltene på datamodellen
* Opprettet funksjon for å plukke ut skårene for de to aksene basert på Category og Criteria (se nærmere beskrivelse i #666)
> Added fields for criteria and scores 

- Assessments.Mapping/AlienSpecies/AlienSpeciesAssessment2023Export.cs
Fixes #676. Dette er begynnelsen på eksporten som brukere av Fremmedartslista 2023 vil ha nytte av for å bl.a. inspisere og filtrere på resultater.
- La til felt som omhandler taksonomi til den fremmede arten
- La til felt som angir hvilken type fremmed art det er og hvor etablert arten er i Norge i dag
- La til felt for kategori og utslagsgivende kriterier
> Export: taxonomy and criteria

- Assessments.Shared/Helpers/Extensions.cs
legger til sjekk om enum har gyldig verdi
gjør at parametere som brukes til andre ting enn spørringen ikke blir tatt hensyn til, f.eks "Area"
> Add type check to enum extension (fix #678)

- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023ExportProfile.cs
bruker displayname på "alienspeciescategory" i stedet for enumverdien i eksporten
close #685
> Map alienspeciescategory displayname in export (#685)

- Assessments.Frontend.Web/Controllers/Api/AlienSpeciesController.cs
- Assessments.Frontend.Web/Program.cs
fjerner parameter som er delt med view'et, og legger heller inn noen utvalgte parameter (gjør det enklere å filtrere data i api'et)
legger til innstilling for json i prosjektet - slik at enum blir vist som tekst og ikke tall
api'et ligger på https://localhost:44321/swagger/index.html
det er metoden GET /api/alienspecies/2023 som nå har filter på navn og kategori
close #686
> Replace api filter parameters (#686)

- Assessments.Frontend.Web/Controllers/AlienSpeciesController.cs
- Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
- Assessments.Frontend.Web/Models/AlienSpeciesViewModels.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Filters.cshtml
Fixes #687
Har lagt til støtte i kontrolleren for å fjerne søkestrengen. 
Omskrevet hvordan filter fjernes til samme måte. Filtrene ble ikke fjernet fra søkestrengen tidligere heller, så deling av lenker hadde potensielt blitt kjipt.
> bugfix - "fjern søk"-knappen

- Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterItemHelpers.cs
- Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
- Assessments.Frontend.Web/wwwroot/css/filter.css
- Assessments.Frontend.Web/wwwroot/js/filter.js
- Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
- Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs
Fixes #698 
Trodde først denne koden ville føre til konflikter med kode som ikke ennå er merget inn, men dette filteret fantes fra før, så jeg tror vi berger bra. 😄 
Og muligens vil det komme en oppdatering i hvordan FA4.EvaluatedScientificName ser ut også. Inntil videre gjør denne koden jobben, så får vi heller fjerne/endre denne koden når dataen kommer på plass. Er jo mange vurderinger som ikke har noen rank...
> Fullfører filter for taksonomisk rank

- Assessments.Frontend.Web/Infrastructure/AttributeHelpers.cs
- Assessments.Frontend.Web/Program.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/_AlienSpeciesHeader.cshtml
- Assessments.Frontend.Web/Views/AlienSpecies/AlienSpeciesHome.cshtml
- Assessments.Frontend.Web/Views/Home/Index.cshtml
- Assessments.Frontend.Web/Views/Shared/_PageMenuHistorical.cshtml
funksjonen som sjekker miljø går mot "Production" og ikke "Development" slik den opprinnelig var ment å gjøre
(slik at vi kan bygge til alle miljø og fremdeles ikke vise fremmedartslista)
> Modify not ready for production (#679)

- Assessments.Mapping/Assessments.Mapping.csproj
- Assessments.Mapping/RedlistSpecies/Profiles/SpeciesAssessment2021ExportProfile.cs
- Assessments.Shared/Assessments.Shared.csproj
- Assessments.Shared/Helpers/Extensions.cs
Close #718 
gjør om en metode for å fjerne html brukt i rødlista, til en delt utvidelse - forenkler koden som fjerner html fra tekstfelt
eksempel:              
` .ForMember(dest => dest.ExpertStatement, opt => opt.MapFrom(src => src.ExpertStatement.StripHtml()))`
> Convert strip html to extension (#718)

- Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023Export.cs
fikser feltet "Utslagsgivende kriterier 2023" i eksporten 
hadde glemt å gi nytt navn i eksporten når på "Criteria" ble døpt om til "DecisiveCriteria"..
> Fix criteria renamed to decisivecriteria in export (#732)

- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs
erstatter null verdier med tom tekst på "DecisiveCriteria"
fikser spørringen når man bruker filter for Invasjonspotensial
> Add nullsubsitute to decisivecriteria

- Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
- Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs
Følgende er gjort: 
1. Lagt til metode/funksjon for å finne automatisk utregnet 'range' på skår på A-kriteriet (ble ikke lagret på datamodellen i FAB). Her er resultatet avhengig av om det er lav kvantil eller høy kvantil som skal estimeres, samt om arten er risikovurdert som en dørstokkart eller som en selvstendig reproduserende. 
2. Lagt til en linje som manglet i metoden for automatisk utregnet beste anslag for skår på A-kriteriet (den hadde sluppet unna forrige runde..)
3. Mapping av alle felt som er direkte knyttet til A-kriteriet. Jeg har endret navn til samtlige av disse. Jeg har lagt alle på hovedmodellen, men det kan kanskje vurderes om alt med A-kriteriet, eller kanskje alt som har med invasjonsaksen (A, B og C-kriteriet) burde ut i en egen "undermodell"/fil..(?)
> Mapping: invasjonspotensial - A-kriteriet

- Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterItemHelpers.cs
- Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
- Assessments.Frontend.Web/Models/PartialViewModels.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
- Assessments.Frontend.Web/Views/Shared/_Ingress.cshtml
- Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
- Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023SpeciesStatus.cs
Fixes #797 
Fixes #712 (Dette er det samme som #797 @AneMarlene?
Endrer SpeciesStatus fra string til enum.
Håndterer ulike kombinasjoner av mivsmiljø og statuser for artene som vises frem som vist på bildet: 
Teksten er fikset opp i etter bildet ble tatt.
> Toppen av vurderingssiden

- Assessments.Frontend.Web/Controllers/Api/TestController.cs
- Assessments.Frontend.Web/Program.cs
kjører database migrasjon på oppstart (igjen)
skjuler databaseinfo (via api'et) i produksjon
> database migrations in startup, disable database info

- Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_CategoryChange.cshtml
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ExpertStatement.cshtml
Fixes #851 
Skjuler endring i risikokategori for vurderinger som er feil.
Legger også begrunnelse i en p-tag slik at det ser litt bedre ut.
> Misidentified assessments

- Assessments.Frontend.Web/Controllers/AlienSpeciesController.cs
- Assessments.Frontend.Web/Infrastructure/AlienSpecies/AttachmentRepository.cs
vises 404 side i stedet for en feilside når et filvedlegg mangler i azure storage
> Add not found when attachment is missing in blobstorage

- Assessments.Transformation/Helpers/Storage.cs
Har sjekket koden og ser ut som nye vedlegg er erstatning for vedlegg alltid for ny id - derfor 'trygt' å anta at vi kan forenkle opplasting av vedlegg til bare laste opp de id'ene som mangler i blobstorage
> Fix last of #814

- Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskMatrix.cshtml
- Assessments.Frontend.Web/wwwroot/css/riskMatrix.css
Fikses #922
- La inn en mindre størrelse for bitte-bitte små vinduer (under 355px) bare fordi jeg ikke liker at ting ikke ser bra ut alltid
- For mikroskopiske skjermer satte jeg på scrollbar for x-retning. Får være grenser ;)
- endra fra tabell til grid
- satte på kategorinavnene på hvert felt, slik at det er lesbart også om fargene strippes vekk
- sort border rundt alle elementene for å øke kontrast for ikke-darktheme mot det hvite. Det var vanskelig å finne en god border-farge som var tydelig nok uten ramme. Med sort omriss kan vi gå for hvit, som har høy kontrast mot det meste.
- Har også uthevet usikker og gjeldende kategori for å nå krav om å vise på andre måter enn bare farge
- Har av samme grunn lagt på underline på gjeldende.
- Har lagt til en del felter som vises for brukere med …
> Risikomatrise utseende

- Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskMatrix.cshtml
Fix #935 
- Tidligere viste matrisa usikkerhet ned selv om ikke alle utslagsgivende kriterier på y-aksen hadde usikkerhet ned. Feilen var 2-delt: (1) kun utslagsgivende kriterier _med_ usikkerhet ble sammenlignet, men alle må sammenlignes _og_ (2) lista som la til nedre usikkerhet hadde kun med verdier for de kriteriene som faktisk hadde usikkerhet ned. Begge disse bugene er nå fikset.
- Tok meg samtidig friheten til å korte ned litt på koden for usikkerhet oppover - og med det ble koden nøyaktig like lang som før :D
> Fiks matrisebug #935

- Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Fixes #979 
Grunnen til krasjen er at artsgruppen mangler på vurderingen. Jeg legger inn så det tillates i koden.
> site does not crash if an assessment has no species group

- Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_CategoryChange.cshtml
Fjerner begrunnelsen for endring av kategori fra 2018 inntil den slås på igjen.
> disable ReasonsForChangeOfCategoryDescription

- Assessments.Frontend.Web/Controllers/AlienSpeciesController.cs
- Assessments.Frontend.Web/Models/PartialViewModels.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
- Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Filters.cshtml
- Assessments.Frontend.Web/Views/Shared/_ControlButtons.cshtml
- Assessments.Frontend.Web/appsettings.Development.json
- Assessments.Frontend.Web/appsettings.Staging.json
- Assessments.Frontend.Web/appsettings.json
- Assessments.Shared/Options/ApplicationOptions.cs
Close #1004
samler alle innstillinger for innsynet i en innstilling "IsHearing" som styrer om eksport, sitering, tilbakemeldinger og statistikk vises
`  "IsHearing": true, // toggles feedback (enabled if true) and export/citation/statistics (disabled if true) during "innsynet"`
> Add and consolidate "hearing" configurationsettings

- Assessments.Transformation/TransformAlienSpecies.cs
close #1024
eksluderer vurderinger med id 4937, 4963, 4964, 4965, 5217 (husdyrraser)
4937	Capra aegagrus subsp. hircus f. 'kystgeit'
4963	Ovis aries 'gammelnorsk sau'
4964	Bos taurus 'skotsk høylandsfe'
4965	Equus caballus 'shetlandsponni'
5217	Sus scrofa subsp. domesticus f. 'ullgris'
hardkodede id'er siden det ikke er mulig å få til en spørring akkurat nå (pga en feil i "NameHiearchy" på en av vurderingene)..
> Exclude certain livestock breeds

- Assessments.Frontend.Web/wwwroot/js/toggleStatView.js
Det kom en feilmelding i konsollen. Denne er nå borte. 
Filter ser ut til å fungere i både rødlista og fremmedartslista.
> fix bug where trying to set type to button where none exists

- Assessments.Data/Assessments.Data.csproj
- Assessments.Data/AssessmentsDbContext.cs
- Assessments.Data/Migrations/20230222090549_AddDataProtectionKeys.Designer.cs
- Assessments.Data/Migrations/20230222090549_AddDataProtectionKeys.cs
- Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
- Assessments.Frontend.Web/Program.cs
det logges mange feil av typen "Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted." regner med det er pga lastbalanseringen i drift
forsøker løsning med konfigurering av "Data Protection":  https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0
> Add dataprotection, attempt to fix antiforgery issues

- Assessments.Frontend.Web/appsettings.json
oppdaterer konfigurasjonen (som det er gjort kun i master akkurat nå)
gjør at fremmedartslista 2023 vises i produksjon (slik den skal under innsynet)
> Enable alienspecies

- Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
- Assessments.Frontend.Web/Models/PartialViewModels.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RegionalSpread.cshtml
Fixes #1028 
Legger til en linje med AreaOfOccupancyInStronglyAlteredEcosystems. 
Vises ikke i innsynet.
> add text for strongly altered ecosystems in regional spread

- Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023Export.cs
- Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023ImpactedNatureTypes.cs
- Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023AreaOfOccupancyInStronglyAlteredEcosystems.cs
- Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023SpeciesStatus.cs
- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023ExportProfile.cs
- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs
- Assessments.Mapping/AlienSpecies/Source/FA4Vurdering.cs
Har gjort diverse småting i mapping-prosjektet. Spesielt:
1. La til nytt listeelement i ImpactedNatureTypes (MajorTypeGroup). Dette skal brukes i filtreringen (#1118), og måtte også legges til i kildefilen (FA4). 
2. Ryddet i et par enumer som hadde upresise/feil defaultverdier
3. Fjernet PreConditions i profilen som sjekka om en vurdering var ferdigstilt eller ikke (relevant før innsynet, men ikke nå lengre)
4. La til naturtyper i eksporten.
> Diverse mapping - nytt listeelement på naturtyper til filtermeny

- Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
- Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023SpeciesStatus.cs
Lagt til ny default verdi på etableringsklasse. Dette er en default verdi som kun angår arter som ikke har angitt etableringsklasse, og er altså en verdi som aldri skal vises (se også #1113).
> Fix mapping species status

- Assessments.Frontend.Web/Controllers/AlienSpeciesController.cs
fjerner feil når liste med ekspertgruppemedlemmer hentes (feil med ny referanse etter oppdatering)
> Fix getting expertgroupmembers after update

- Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_CriteriaExplanation.cshtml
- Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
- Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023Export.cs
- Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs
Jeg har gått gjennom alle felt på datamodellen og fjernet termen "RiskAssessment" fra navnene. 
Fix #749
> Fjern termen RiskAssessment fra alle felter på datamodellen

- Assessments.Frontend.Web/Models/PartialViewModels.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_View.cshtml
- Assessments.Frontend.Web/Views/Shared/_ListView.cshtml
Fixes #1171 
Legger til HasEffectWithoutReproduction som også får dørstokkikon.
> add HasEffectWithoutReproduction to doorknocker icon assessments

- Assessments.Frontend.Web/wwwroot/css/listview.css
Artsgruppenavnet går nå kun på to linjer:
> fix too narrow width on list icon species group text

- Assessments.Frontend.Web/wwwroot/css/site.css
Flytter meny-knappen til venstre side i henhold til punkt 1 på issue #555
> move menu button from right to left side on mobile devices

- Assessments.Frontend.Web/Models/PartialViewModels.cs
- Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
- Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/SpeciesAssessment2021.cshtml
- Assessments.Frontend.Web/Views/Shared/_CategoryDescription.cshtml
- Assessments.Frontend.Web/Views/Shared/_ListView.cshtml
- Assessments.Frontend.Web/wwwroot/css/bnw.css
- Assessments.Frontend.Web/wwwroot/css/categorybar.css
- Assessments.Frontend.Web/wwwroot/css/listview.css
This reverts commit fadd7ce50780f26609cb1995d4fe8d99346394cf, reversing changes made to a5765d432ce80f83b9f9a2429497933c0e33693c.
> Revert Merge pull request #1370 Kategoribar

- Assessments.Frontend.Web/Infrastructure/AlienSpecies/StatisticsHelper.cs
Closes #1403 
Denne pr'en løser de to siste check-boksene i issue #1403: 
1. Feil i detaljert spredningsfigur, som skal telle hver spredningsvei én gang per vurdering. 
2. Feil i tellingen på antall vurderinger i enkelte artsgrupper i artsgruppe-figuren.
> Bugfix - fix figure counts
