Artsdatabanken/Assessments

Assessments.Frontend.Web/Views/Shared/_Categorybar.cshtml
Assessments.Frontend.Web/Views/Test/SpeciesAssessment2021.cshtml
Assessments.Frontend.Web/wwwroot/css/categorybar.css

Kategoribaren som fantes fra før hadde for lav kontrast i følge universell utforming, og manglet kategorien NE.
Har derfor laget den på nytt. Den er ennå ikke tilpasset mobil, men det er kun justeringer i css, og kan komme senere.
Partial-komponenten setter korrekt kategori som aktiv basert på input fra modellen for arten man er på.

Kategori-bar 

---

Assessments.Frontend.Web/Views/Test/partials_2021/_Pavirkningsfaktorer.cshtml
Assessments.Frontend.Web/wwwroot/css/site.css

- less reliant on hierarchy.
- less formatting of strings from db
- less guessing of where things should belong leading to potential misleasing hierarchy
- added icons to presentation.

impact factors are now presented in a more readable way 

---

Assessments.Frontend.Web/Views/Test/SpeciesAssessment2021.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/Kriterier_2021/_Kriterie_Automatic.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/Kriterier_2021/kriterier.json
Assessments.Frontend.Web/Views/Test/partials_2021/_Fylkesforekomster.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/_Fylkesforekomster_visning.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/_Habitat.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/_Informasjon.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/_Oppsumering.cshtml
Assessments.Frontend.Web/wwwroot/css/site.css

Må lagre før det er ferdig pga. api-endring.

Begynt på flytting og forbedring av tekst. 

---

Assessments.Frontend.Web/Connected Services/AssessmentsODataService/AssessmentsODataService.cs
Assessments.Frontend.Web/Connected Services/AssessmentsODataService/AssessmentsODataServiceCsdl.xml

Synkroniserte klientkoden med api'et (på test: https://assessmentsapi.test.artsdatabanken.no/api/)

Update odata service

---

Assessments.Frontend.Web/Views/Shared/glossary.json
Assessments.Frontend.Web/Views/Test/partials_2021/_Fylkesforekomster.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/_Habitat.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/_Informasjon.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/_Oppsumering.cshtml
Assessments.Frontend.Web/Views/Test/partials_2021/habitat.json
Assessments.Frontend.Web/wwwroot/css/site.css

- korrigerte feil
- skjul irrelevante habitat
- justere noe css

Habitat improvements

---

Assessments.Frontend.Web/Views/Shared/_CategoryDescription.cshtml
Assessments.Frontend.Web/Views/Shared/glossary.json
Assessments.Frontend.Web/Views/Test/partials_2021/_Informasjon.cshtml

- Small adjustments to category descriptions and text on oneliners. Added html. A few space fixes.
- Before merge: Needs to fetch html from json in edited fields

Adjustments glossary.json

---

Assessments.Frontend.Web/Views/Shared/glossary.json

Shortened category descriptions to be more "on point". Fixed my own silly mixup of "ikke vurdert"/"ikke egnet" in oneliners from previous edit.

please update glossary.json

---

Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
Assessments.Frontend.Web/Controllers/Api/Redlist2006Controller.cs
Assessments.Frontend.Web/Controllers/Api/Species2015Controller.cs
Assessments.Frontend.Web/Controllers/Api/Species2021Controller.cs
Assessments.Frontend.Web/Controllers/Api/TestController.cs
Assessments.Frontend.Web/Controllers/BaseController.cs
Assessments.Frontend.Web/Controllers/TestController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Infrastructure/ODataModelConfiguration.cs
Assessments.Frontend.Web/Startup.cs
Assessments.Frontend.Web/wwwroot/js/swagger.js

lagt til api med støtte for swagger og odata

Add odata api

---

Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
Assessments.Frontend.Web/Controllers/TestController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/Test/List2021.cshtml
Assessments.Mapping/Models/Species/SpeciesAssessment2021Export.cs
Assessments.Mapping/SpeciesAssessment2021Profile.cs

støtte for eksport til excel via listevisningen (inkludert valgt filter)
modellen for en vurdering til eksporten må utvides når spesifikasjonen blir klar

Add basic excel export (#94)

---

Assessments.Frontend.Web/Controllers/TestController.cs
Assessments.Frontend.Web/Models/RL2021ViewModel.cs

lagrer statistikk i modellen for listevisningen, klart for bruk i visningen

Add statistics model

---

Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
Assessments.Frontend.Web/Views/Redlist/List/List2021.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_Breadcrumb.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_Header.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_Introduction.cshtml
Assessments.Frontend.Web/wwwroot/css/listview.css

henter ut antall arter per. kategori. 
Så langt bare en mini-visning med css, ikke en ferdig fancy statistikkviser.

En liten mini-statistikk av antall arter i listen generelt. 

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Models/RL2021ViewModel.cs
Assessments.Frontend.Web/Views/Home/Index.cshtml
Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Breadcrumb.cshtml
Assessments.Frontend.Web/Views/Redlist/Index.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/Views/Redlist/SpeciesGroup.cshtml
Assessments.Frontend.Web/wwwroot/json/speciesgroup.json
Assessments.Mapping/Models/Species/SpeciesAssessment2021.cs

- Add filter for presume extinct
- add filter for region occurences
- fix bug in category filter, where categories with degree ("º") was skipped
- add "Sekkdyr" to speciesgroup.json

More filters

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Ingress.cshtml
Assessments.Frontend.Web/Views/Shared/_Category.cshtml

Fixed category bug, added simple text in intro about year/need 4 revision.

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Models/RL2021ViewModel.cs
Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/searchAndFilter.css

Legger til filter for artsgruppe.

Filter artsgruppe

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Models/RL2021ViewModel.cs
Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/listview.css
Assessments.Frontend.Web/wwwroot/css/searchAndFilter.css

Legger til filter for hovedhabitat

add habitat filter

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/ExportHelper.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Mapping/Models/Species/SpeciesAssessment2021Export.cs
Assessments.Mapping/SpeciesAssessment2021ExportProfile.cs

@matssa kan du sjekke at eksporten (fremdeles) virker?

Add region occurrences to export (#94), separate export helper

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_ExpertCommitteeMembers.cshtml

Add (hardcoded) date

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_ListView.cshtml
Assessments.Frontend.Web/Views/Shared/_PageMenu.cshtml
Assessments.Frontend.Web/wwwroot/css/listview.css
Assessments.Frontend.Web/wwwroot/css/searchAndFilter.css
Assessments.Frontend.Web/wwwroot/css/site.css

- Lagt til riktige regioner (fra db)
- Lagt inn populærnavn til listevisningen
- søk er nå alltid synlig på mobil
- knappen for å åpne filter fungerer som den skal

Artsnavn og regioner

---

Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/searchAndFilter.css

- Added black transparent layer
- fixed css-gap (removed any code for 750, changed 650 to 750 px in list&search)

Mobile modal fix

---

Assessments.Frontend.Web/Infrastructure/ExportHelper.cs
Assessments.Mapping/Helpers/Extensions.cs
Assessments.Mapping/Models/Species/CategoryChangeReason.cs
Assessments.Mapping/SpeciesAssessment2021ExportProfile.cs

utvidet eksporten (igjen), refaktorert litt
kan du sjekke at det fungerer igjen @matssa?

Excel export

---

Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml

Fjerner bug ved med at siden kresjer ved flere åpne filtre

remove remember open filters

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/ExportHelper.cs
Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Mapping/Helpers/Extensions.cs
Assessments.Mapping/SpeciesAssessment2021ExportProfile.cs

eksportknapp (og excelfilen) åpnes i ny fane (forbedrer opplevelsen litt siden eksport tar tid og man slipper å laste siden i tillegg)
la til ekspertgruppemedlemmer i nytt ark
diverse justeringer på ulike felter
satt fast bredde på kolonner for vurderinger

More export

---

Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/searchAndFilter.css

Add a simple display of active filters. 
This can me made a lot fancier, but I think this is sufficient for now.

simple display of active filters

---

Assessments.Frontend.Web/Controllers/RedlistController.cs

Legger til søk på populærnavn
Eksakt match legges først i resultatene. Eks søk på "Laks" vil ha "Salmo salar" som første treff. (#85)

Søk på populærnavn

---

Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Criteria.cshtml

- it's supposed to look mostly the same
- BUT fixed some minor issues
- B - criteria no longer displays fancy graph
- C - criteria main level now also displays mmpi data

Criteria consolidation to easier figure out bugs

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Habitat.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_Graphs.cshtml
Assessments.Frontend.Web/wwwroot/json/habitat.json

Habitat add shortname

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_CategoryChange.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_ListView.cshtml
Assessments.Frontend.Web/Views/Shared/_Category.cshtml
Assessments.Frontend.Web/Views/Shared/_Categorybar.cshtml
Assessments.Frontend.Web/wwwroot/json/glossary.json

#157 - category substring check missing

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs

Able to search on all taxonomic levels (nothing yet to indicate this, but searching is possible)

Search taxon trail

---

Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/searchAndFilter.css
Assessments.Frontend.Web/wwwroot/js/site.js

- use actual button elements to open filter elements with js
- no js = always open
- collapse filters initially

Better filter

---

Assessments.Frontend.Web/Controllers/RedlistController.cs

make species group searchable

---

Assessments.Frontend.Web/Controllers/RedlistController.cs

Søk på "jervrapp" (art) vil også gi treff på "tuerapp" og "matterapp" (underarter/varieteter av jervrapp)

search on popular name also gives match on subspecies

---

Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/js/site.js

The mark all redlisted/endangered filter option now actually marks them before submitting. 
This allows turning them off again, which previously didn't work. I also toggles them for mobile devices.

Toggle redlist and endangered

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Habitat.cshtml
Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_ImpactFactors.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/site.css

There is still room for improvement, especially on mobile and regarding the "se mer" button and content. 
But this is a big enough change for now.

Habitat improvements per discussion

---

Assessments.Frontend.Web/Controllers/RedlistController.cs

Kriteriefilteret fungerte ikke. 
Nå gjør det det igjen.

criteria filter bug fix

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Fylkesforekomster_visning.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/site.css

- Removed the empty boxes
- made a line between list elements
- added a header to the list
- added a color explanation on the bottom
These things makes the list prettier imo. 
This is not regarded as a final look, but an iteration towards it.

change region list of geographic distribution

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_ExpertStatement.cshtml

Se forklaring og relatert spørsmål i #236
Konklusjon på spørsmål var ja: merg denne inn.
Kan eventuelt slette utkommenteringen permanent.

Ekspertuttalelse, LC,NA,NE

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Development.cshtml
Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Links.cshtml
Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_SidebarContent.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/categorybar.css

Kategoribar -> Det er ennå litt finplukk å bestemme seg for og justere for enkelte kategorier for å nå UU-kravene, men hovedkonseptet er på plass. 
Historikk -> Utvikling. I fremtiden kan vi legge til piler også ?
Ny boks i sidebar -> Videre lesning
Mulig mobil bør justeres litt mer også senere

Categorybar - Rough changes

---

Assessments.Frontend.Web/Views/Redlist/Assessment/partials/_Development.cshtml
Assessments.Frontend.Web/Views/Redlist/List/partials/_ListView.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/categorybar.css
Assessments.Frontend.Web/wwwroot/css/site.css

UU contrast fix for text sized elements:
UU contrast fix for large elements:
+ big first letter and no italics.

Category colour updates + category text css

---

Assessments.Frontend.Web/Views/Redlist/List/partials/_ListView.cshtml
Assessments.Frontend.Web/wwwroot/css/listview.css
Assessments.Frontend.Web/wwwroot/css/site.css

fixed bold, wrap and capitalisation of listview, focused on mobile
for mobile we accept only following WCAG AA for the popular name, not AAA, as lighter colour for this text makes it easier to separate the scientific name from the popular name, thus increasing list readability,

Text presentation for list

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/Redlist/List/partials/_Filters.cshtml

fjerner også samtidig kategorier fra constants og benytter heller json-fila

Legger til navn til kategorier i filteret

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml
Assessments.Frontend.Web/wwwroot/json/kriterier.json

- Endret alle <= til ≤
- la til manglende ≤ (comparator) for C1
- Korrigerte tekst for 5%, men etter matrisen. Ble riktig tror vi :)

fixes #332

---

Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Artsnavn.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_ListView.cshtml
Assessments.Frontend.Web/wwwroot/css/listview.css

Fikser hybridnavn 

---

Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Development.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_SpeciesGroup.cshtml
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/json/kriterier.json

Se commitbeskjed.
Det som ikke er dekt i refererte issues som skal lukkes er flyttet inn i nye issues.
fixes #308  
fixes #265
fixes #331 (fordi Bai og Baii er to egne issues så da tar vi dem der)

Masse minifikser i en

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Breadcrumb.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/List.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Graphs.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Header.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_InfoGraphics.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Search.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/Rodlisteforarter.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/Shared/_PageMenu.cshtml
Assessments.Frontend.Web/wwwroot/css/categorybar.css
Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/css/site.css

Mye småplukk.
Litt css.
Noen piler.
Noe fjerning av farge.
Nor plassering av søkefelt

Små forbedringer på listesiden

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Search.cshtml
Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/js/search.js

fix #338 
Legger til søkeforslag. 
Har formatert latinsk navn likt som i listevisninga. 
Default sortert liste etter vitenskapelig navn.

Improve search

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Search.cshtml
Assessments.Frontend.Web/wwwroot/css/search.css

- Setter søkeknappen tilbake på plass
- Justerer lengden på søkeforslagfeltet

fix searchbar button misplaced and witdh of suggestions

---

Assessments.Frontend.Web/Infrastructure/Helpers.cs

som nevnt i #310 trenger vi bedre sortering. 
Denne fikser bedre sortering.

improve sorting

---

Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
Assessments.Mapping/Assessments.Mapping.csproj
Assessments.Transformation/Assessments.Transformation.csproj

Oppdaterte nuget pakker som dependabot peker på er kommet i ny versjon.. oppgraderte kun de som er kompetible med .net core 5
Ser fint ut når jeg kjører løsningen lokalt

Upgrade some nuget packages - dependabot

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/wwwroot/js/search.js
Assessments.Mapping/Helpers/SpeciesAssessment2021ProfileHelper.cs
Assessments.Mapping/Models/Source/Species/Rodliste2019.cs
Assessments.Mapping/SpeciesAssessment2021Profile.cs

#356 lagt til i scientificname streng
#354 supplert med info fra driftbase - må endres kode for å ta hensyn til taxonrank

Diverse taksonomi fikser

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs

Form finnes ikke lenger. Dvs. de er fjernet da de ikke er aktuelle for rødlistevurdering.

remove filter on form

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/List/List.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_ListView.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Paginator.cshtml
Assessments.Frontend.Web/wwwroot/css/listview.css

move paginator under list

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/site.css

Fjerner label fra sortering 
endret styling noe

improve styling for select sorting and remove label

---

Assessments.Frontend.Web/Views/Redlist/Species/Rodlisteforarter.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/Shared/_PageMenuHistorical.cshtml

endre navn på alle 'Rølista' til 'Rødlista'
Fix spelling of 'Rødlista'on #388

Rølista -> Rødlista

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_CategoryChange.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Regions.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_SidebarContent.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_SpeciesGroup.cshtml

"Småplukk"

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Citation.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Search.cshtml
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/graphs.css
Assessments.Frontend.Web/wwwroot/css/listview.css
Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/js/search.js

Synonym og søkestrenger

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Ingress.cshtml

fixes #405
logic flaw fixed. 
easy is better.

fixes #405

---

Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/js/search.js

fikset issue med at spans ble brutt opp når man søkte på "span" osv.
generelt håndterte flere issues med fargematcheren

Fikset farge-og span-matching issues

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_ImpactFactors.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/tabs.css

fixes #417 and also css-bordering for table on first level and wrongly aligned border for impact table

påvirkningsfaktortabellen

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Development.cshtml
Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
Assessments.Frontend.Web/Views/Shared/_PageTopBar.cshtml
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/js/assessmentTabs.js

Fremdeles mye som gjenstår på denne både mtp. pilnav, uu-krav generelt, toggle osv, MEN nå er det ihvertfall pakka pent inn i menyen i toppbaren, og sånn sett ikke øyeskjærende slik knappene har vært frem til nå.

Temaknapp inn i meny

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Development.cshtml

kun vis vurderinger med assesmentyear 2021 som 2021 i utviklingsfanen

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml
Assessments.Frontend.Web/wwwroot/json/glossary.json

To små tekstlige issues fiksa

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Graphs.cshtml
Assessments.Frontend.Web/wwwroot/css/site.css

Får være for nå
Har jeg glemt noen?

Kategoritekst fix

---

Assessments.Frontend.Web/Controllers/RedlistController.cs

if no search results, return no results

---

Assessments.Frontend.Web/Views/Home/Index.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_CategoryDescription.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Development.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Habitat.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_InclusionCriteria.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Links.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_NoCriteria.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_SidebarContent.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/Shared/_RedlistHeader.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/graphs.css
Assessments.Frontend.Web/wwwroot/css/rl2021.css
Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/js/search.js

fixes #450
fixes  #444
fixes  #445
fixes #435
fixes  #440

Links and buttons

---

Assessments.Frontend.Web/Startup.cs

slår av swagger (bortsett fra i utvikling/lokalt) etter diskusjon

Disable swagger except in development (#457)

---

Assessments.Frontend.Web/Controllers/RedlistController.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Citation.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Citation.cshtml
Assessments.Frontend.Web/wwwroot/css/site.css

fix #453 
Fikser også bug med paginering etter å ha fjernet filter. 
fjerner overflow fra sitering på mobil på listevisningen

remove search and filter properly

---

Assessments.Frontend.Web/wwwroot/css/listview.css

fix #406 
Har ikke med bindestrek på ord som går over to linjer. Det skal sies at jeg har forsøkt å få det med...

break word

---

Assessments.Frontend.Web/Views/Home/Index.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/Rodlisteforarter.cshtml
Assessments.Frontend.Web/wwwroot/css/graphs.css
Assessments.Frontend.Web/wwwroot/css/site.css

Mobile fixes

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Breadcrumb.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Habitat.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_SidebarContent.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_SpeciesGroup.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Breadcrumb.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_ListView.cshtml
Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/css/site.css

- alt tekster
- ol i steden for ul
- fiksa en hierarkisk sak

Fikser en del element fra accessibility report

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_CategoryDegrade.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_RegionStatistics.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css

"Småplukk 3" - minifeil på vurderingssidene

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/js/filter.js

Må testes godt, men nå skal altså knappene for å oppdatere filter når åpen alltid være synlige + litt cssendringer

filter now has buttons inside screen at all times

---

Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/js/assessmentTabs.js

- Use javascript to detect user preference for high contrast and dark theme. 
theme still does not persist on manual change by button, but at least system set preferences will persist, giving a lot smoother experience.

dark mode detection - javascript

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Criteria.cshtml

Legger til konklusjon for c-kriteriet også.
Ja, det er duplisert kode. Sry.

C - konklusjon

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Citation.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/bnw.css

fixes #472
fixes #484
- fikser litt små kontrastendringer og slikt på har + høykontrast for å oppnå 100% på automatisk test.
- svg kart på dark mode er nå i dark mode.

Darkmodeadjustments

---

Assessments.Frontend.Web/Infrastructure/Filter.cs
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_ControlButtons.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_FilterHeader.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_FilterMobileButtons.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/js/filter.js

Planen var å justere på filterne i form av chips osv, men det var så vanskelig å finne frem.
Begynte derfor å minimere koden litt, og tok ut to områder med ren html til egne bittesmå partials.
Mer kunne vært gjort for å minimere kode her, men dette for gå for denne gang. Jeg fant det jeg lette etter.

Litt refactor på filter

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Breadcrumb.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/List.cshtml
Assessments.Frontend.Web/wwwroot/css/bnw.css

Denne må nok bli endret videre igjen når historiske vurderinger er oppe og kjører i samme løsning.
inntil det -> ha den slik.
+ fiksa noen darkthemefarger som var litt off

breadcrumb etter ønske.

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/css/site.css

anticrunch

---

Assessments.Frontend.Web/Infrastructure/Helpers.cs

Sortering av populærnavn sorterte de uten navn først. Nå er dette endret.

popularnames sorted properly

---

Assessments.Frontend.Web/Views/Home/Index.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_MapSvalbard.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_FilterMobileButtons.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/Rodlisteforarter.cshtml
Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
Assessments.Frontend.Web/Views/Shared/_Layout.cshtml
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/js/assessmentTabs.js
Assessments.Frontend.Web/wwwroot/js/filter.js
Assessments.Frontend.Web/wwwroot/js/themes.js
Assessments.Frontend.Web/wwwroot/js/toggleSwitch.js

- themes har flytta til ei ega fil
- fiksa en tittel
- css for å vise/skjule filter kommer nå fra klasse. Men rydding av css her er IKKE i mål. 
- resizing for toggle/checkbox funker nå fint, men mangler ennå reset skjema for resize, så fra mobil til storskjerm blir det feil. uansett, fremgang
- en god del styling inline + id'er er nå senket i prioritet til klassenivå
- begynte så smått å endre om til et lite startup-script på filter, men igjen, ikke i mål.
- noscroll på underlaget
- no js ser ikke ut. men det har den vel egentlig aldri gjort :D

Fix - la det eskalere :|

---

Assessments.Frontend.Web/Views/Home/Index.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/SpeciesAssessment2021.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/List.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/Rodlisteforarter.cshtml
Assessments.Frontend.Web/Views/Shared/_Layout.cshtml

fixes #502 properly this time -> proper title conventions etc.
Etter modellen "undersidetittel - sidetittel - sideeier/hoveddomene"

Ordentlige titler på alle undersider vi har per nå.

---

Assessments.Frontend.Web/Infrastructure/TagHelpers.cs
Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
Assessments.Frontend.Web/appsettings.Development.json
Assessments.Frontend.Web/appsettings.json
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/js/cookies.js

- Forsøk på noe som kan leve midlertidig.
- flytta inline script inni  egen fil for å ha litt ryddigere kode.
- trigges nå kun på rødlista og undersider ikke lister/ osv.
- sessionstorage husker valg
- for test: fjern environment production/staging hvis ikke vil den ikke synes
- mye inline kommentarer så det skal gå fort å få fiksa den opp når man har litt bedre tid
- tenkte å etterhvert bruke sessionstorage til darktheme husking og sånt også.

Cookiewarn

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Breadcrumb.cshtml

corrects breadcrumb bug #546

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_InclusionCriteria.cshtml
Assessments.Frontend.Web/wwwroot/json/glossary.json

endret tre relaterte felt i glossary, og måtte slenge på html raw rundt for å få med italics tag.
fixes #538

 Forklaring på kategori (NA og NE)

---

Assessments.Frontend.Web/wwwroot/js/search.js

fixes #564

---

Assessments.Frontend.Web/Infrastructure/DataRepository.cs
Assessments.Frontend.Web/Infrastructure/Services/ExpertCommitteeMemberService.cs
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Archived.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Breadcrumb.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_CategoryChange.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_CategoryDegrade.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_CategoryDescription.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_Citation.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_SpeciesGroup.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Citation.cshtml
Assessments.Frontend.Web/wwwroot/js/search.js
Assessments.Frontend.Web/wwwroot/json/glossary.json
Assessments.Mapping/Helpers/CategoryAndCriteriaHelper.cs

- Tekstflytting
- Fix på søk
- Sitering.

Januaroppdatering

---

Assessments.Mapping/Assessments.Mapping.csproj
Assessments.Mapping/SpeciesAssessment2021ExportProfile.cs

erstatter regex med en tredjepartskomponent for å fjerne html i eksporten

Replace striphtml regex with helper from HtmlAgilityPack (#572)

---

Assessments.Mapping/SpeciesAssessment2021ExportProfile.cs

fjerner html fra feltet "Begrunnelse nedgradering av kategori" i eksporten

Strip rationalecategoryadjustment html in export (#572)

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml

fix bug 'using System.Linq' appears under search bar

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Filters.cshtml

oppdaterte sortering - litt for å teste paginering og at parametere fungerer
får legge til flere felter som det skal sorteres på når de blir tilgjengelig i datakilden

Add sorting (default and by query parameter)

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterHelpers.cs
Assessments.Frontend.Web/Infrastructure/EstablishmentCategory.cs
Assessments.Frontend.Web/Models/AlienSpeciesViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Filters.cshtml
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/toggleSwitch.css
Assessments.Frontend.Web/wwwroot/js/filter.js
Assessments.Frontend.Web/wwwroot/js/toggleSwitch.js

- Legger til filter for "Etableringsklasse i dag" i viewet. Venter til modellen er på plass med backend (#630)
- Omstrukturerer litt i _Filters partial fila for alien species. Nå lages alle filter med den samme koden og ingen filter er hardkodet.
- Lagt til "Merk alle" på filtergrupper og undergrupper
- Endret litt i filter.js for å få merk alle til å fungere. 
For filter.js er hele fila endret, ettersom den var feil indentert. Så den ser værre ut enn den er.

EstablishhmentCategory og "merk alle"-filter

---

Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023Category.cs
Assessments.Transformation/TransformAlienSpecies.cs
Assessments.Transformation/TransformRedlistSpecies.cs

lagt til endel filter i spørring mot databasen og under transformering som tar bort ugyldige vurderinger 
fjernet også "Ukjent" fra kategori
publiserer nye filer når denne er i develop, som også må tas i bruk av alle - siden det kan bli feil når eldre datafiler har ugyldig kategori
close #651

Exclude assessments

---

Assessments.Frontend.Web/Controllers/AlienSpeciesController.cs
Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
Assessments.Frontend.Web/Infrastructure/Extensions.cs
Assessments.Frontend.Web/Models/AlienSpeciesViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Filters.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_ListView.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Search.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_View.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/_ViewImports.cshtml

fjerner "parameter" fra querystring, close #694 
gjort om/forenklet logikk på fjern søk og fjern filter, slipper videresending

Optimize querystring parameters (#694)

---

Assessments.Shared/Helpers/Extensions.cs
Assessments.Tests/Assessments.Tests.csproj
Assessments.Tests/Extensions/ExtensionTests.cs

gjør det enklere å fjerne html fra tekst, og beholde enkelte tagger `<p>, <i> og <b>`
la til unit tester som kan brukes for å teste koden
Close #720

Add remove unwanted html extension (#720)

---

Assessments.Frontend.Web/Dockerfile
Assessments.Frontend.Web/Infrastructure/ExportHelper.cs
Assessments.Frontend.Web/Program.cs

fikser problemer med eksport i excel på linux (Calibri mangler, erstatter med Carlito ("a free replacement for the MS (proprietary) font")

Add fallback font (fix linux excel export)

---

Assessments.Frontend.Web/Infrastructure/Extensions.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Filters.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Paginator.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Paginator.cshtml

Fix #739 
endret metoden til å returnere querystring som tekst, med enklere logikk
bør teste litt at det fungerer på rødlista også..

Modify querystring extension, fix parameters bug

---

Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/SpeciesAssessment2021.cshtml
Assessments.Frontend.Web/Views/Shared/_CitationForAssessment.cshtml

Bruk "Sitering" som overskrift for sitering på alle lister

---

README.md

forsøk på å oppdatere/rydde litt på readme - spesielt slik at man får oversikt over ulike miljø og hvordan de bygges
setter pris på innspill

Update readme (#679)

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/partials/_RevisionReason.cshtml

Fix #787 
La til sjekk om vurdering har revisjon på lenke til tidligere utgave (som ellers ville lenket til side med 404 ikke funnet)

Make sure revisions exist before adding link (#787)

---

Assessments.Frontend.Web/wwwroot/css/assessment.css

denne kan du egentlig bare dytte rett inn.

tiny css fix

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_CategoryChange.cshtml

Fikser bugs i endring i risikokategori.
Fixes #807 
Fixes #776 
Fixes #775

fix bug in risk category change

---

Assessments.Frontend.Web/Controllers/FeedbackController.cs

Close #860
endret tekst og avsender på e-post for validering av e-postadresse

Modify email text and sender

---

Assessments.Frontend.Web/Views/Shared/_Feedback.cshtml

Close #869
Deaktiverer knappen i skjema for tilbakemelding, når skjema er gyldig og det sendes til server

Disable button when submitting (valid) form

---

Assessments.Frontend.Web/Controllers/FeedbackController.cs

endrer plassering for filer (fra tilbakemelding) som lastes opp til azure
lagres i blob som heter "feedback", og har med type (f.eks "AlienSpecies"), år og id (fra databasen) i filnavnet

Modify feedback file blob and folder

---

Assessments.Frontend.Web/Infrastructure/Enums/AssessmentType.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/_AlienSpeciesHeader.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/SpeciesAssessment2021.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/List.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/_RedlistHeader.cshtml
Assessments.Frontend.Web/Views/Shared/_PageMenu.cshtml

Fixes #656 
Legger inn sidemenyen fra Drupal.

Meny fra drupal

---

Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_Attachments.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_GeographicVariationInCategory.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ImpactedNatureTypes.cshtml

Fixes #906 
Skjuler filvvedlegg, geografisk variasjon i utbredelse og naturtypetilhørighet dersom vurderingen har skjedd på et annet nivå.

Assessed at another level

---

Assessments.Transformation/Helpers/Storage.cs

Fixes #902 
Legger til 
- ThreatenedNatureTypesAffectedDomesticDescription
- CommonNatureTypesAffectedDomesticDescription
fra RiskAssessment og legger til et felt i lista ImpactedNatureTypes
- IsThreatened

Risikoforklaring for F og G-kriteriet

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
Assessments.Frontend.Web/appsettings.Development.json
Assessments.Frontend.Web/appsettings.Staging.json
Assessments.Frontend.Web/appsettings.json
Assessments.Shared/Options/ApplicationOptions.cs

Fixes #917 
Legger til en variabel for å skjule sitering på samme måte som vi skjuler eksport til innsynet

add option for removing citation

---

Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023MicroHabitat.cs
Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs

Lista som inneholder informasjon om livsmiljø er mappet. Denne pr'en inneholder dataen som brukes i #932.

Mapping av livsmiljø

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs

Fixes #941 
Lar være å tenkte på hybridtegn ved sortering

Remove "×" from name for sort order

---

Assessments.Frontend.Web/Infrastructure/Constants.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_AssessmentReasoning.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_Attachments.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_CategoryChange.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ClimateEffectsInvationpotential.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_Conclusion.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ExpertStatement.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_GeographicVariationInCategory.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ImpactedNatureTypes.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RegionalSpread.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskCategoryExplanation.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_SpreadWays.cshtml
Assessments.Frontend.Web/Views/Shared/_CitationForAssessment.cshtml
Assessments.Frontend.Web/Views/Shared/_Feedback.cshtml
Assessments.Frontend.Web/Views/Shared/_Reference.cshtml
Assessments.Frontend.Web/Views/Shared/_TableOfContents.cshtml
Assessments.Frontend.Web/wwwroot/css/assessment.css

fixes  #885
- tweaket bittelitt på big-data-table
- Fikser spredningsveier alle tre fanene, som oppgitt, men:
- trenger første is-visbile-sjekk i rigget til @matssa 
- H2 & H3 -> TableOfContents + anker lenker @matssa 
- Det er masse tomme enumstrenger (eks. MainCategory.Name). Disse må hete noe så tabellen gir mening. (Se mld i chat) @AneMarlene

Spread Ways 

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_Attachments.cshtml

Fixes #871 
Setter opp filvedlegg i en tabell

make file attachments show in a table

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_ImpactedNatureTypes.cshtml

Legger til livsmedium til naturtypetilhørighet

---

Assessments.Frontend.Web/Views/AlienSpecies/_Layout.cshtml
Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
Assessments.Frontend.Web/Views/Shared/_Layout.cshtml

Legger til cookie warning på landingssiden

---

Assessments.Frontend.Web/Views/AlienSpecies/_Layout.cshtml

stopper søkemotorindeksering på sidene for fremmedartslista

Temporarily prevent robots indexing (#961)

---

Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/js/filter.js

Fixes #974 
Fixes #973 
Legger også inn noe kode som har fjernet for filter i rødlista. Dette gjorde at man ikke kunne bruke knappene for å velge alle rødlistede eller alle truede arter.

Redlist fixes

---

Assessments.Frontend.Web/Controllers/FeedbackController.cs
Assessments.Frontend.Web/Views/Shared/_Feedback.cshtml

Close #968
fikset lenkene når applikasjonen kjører fra virtuell katalog (iis på hjemmesidene)

Fix feedback redirects and links (#968)

---

Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ProfileHelper.cs
Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023FreshWaterRegion.cs
Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs

Close  #962
legger til "WaterRegionName", hentet fra WaterRegion.geojson i Fremmedartsbase2023 prosjektet

Add waterregionname mapping (#962)

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_CriteriaExplanation.cshtml

Fixes #989 
Legger inn c-kriteriets tabell i forklaringen over kriterier.

add C criteria table

---

Assessments.Frontend.Web/Controllers/FeedbackController.cs

la til ScientificName i epost kvittering for tilbakemelding
Close #999

Add scientificname to feedback email receipt (#999)

---

Assessments.Frontend.Web/Views/Shared/_Feedback.cshtml

Adjust button text 

---

Assessments.Frontend.Web/Infrastructure/Constants.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RegionalSpread.cshtml

remove tab for regional spread

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/AlienSpeciesHelpers.cs

Fixes #1008 
Oppdaterer forklaringen av risikomatrisens x-akse

update explanation for x-axis explanation of risk matrix

---

Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciecAssessment2023AlienSpeciesCategory.cs
Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs
Assessments.Mapping/AlienSpecies/Source/FA4Vurdering.cs

To nye alien species categories og tilhørende felt

new alien species categories for crazy species

---

Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_AssessmentReasoning.cshtml
Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciecAssessment2023AlienSpeciesCategory.cs
Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs

add reasoning texts for two new types of alienSpeciesCategory

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_CriteriaExplanation.cshtml

Fikser at F og G potensielt ikke viser detaljer.

update when to show criteria f and g

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/_AlienSpeciesHeader.cshtml
Assessments.Frontend.Web/Views/Shared/_PageTopBar.cshtml
Assessments.Frontend.Web/wwwroot/css/alienSpecies.css
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/js/collapse.js

- Om oss og meny i headeren vises igjen
- ikonet i headeren blir borte

Header funkyness

---

Assessments.Frontend.Web/Views/Shared/_Feedback.cshtml

Close #1039
Setter domene for cookie til "artsdatabanken.no", når koden kjøres i drift (og sidene kan vises med eller uten www)

Add cookie domain 

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskMatrix.cshtml

account for no uncertaintyValues in risk matrix

---

Assessments.Frontend.Web/wwwroot/css/filter.css

Fixes filter issue for mobile in issue #1050

shrink height of filters to make room for the address bar

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterItemHelpers.cs
Assessments.Frontend.Web/Infrastructure/Constants.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_KnowMore.cshtml
Assessments.Frontend.Web/appsettings.Development.json
Assessments.Frontend.Web/appsettings.Staging.json
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023SpeciesGroups.cs
Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023SpeciesStatus.cs

Fixes #971 
Legger til seksjonen "Vil du vite mer om arten". 
Dette skal ikke vises på innsynet så for å teste dette må du deaktivere "isHearing" development settings eller negere "showKnowMore" i AlienSpeciesDetail.cshtml

Vil du vite mer om arten

---

Assessments.Frontend.Web/Infrastructure/Constants.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/_Layout.cshtml
Assessments.Frontend.Web/appsettings.Development.json
Assessments.Frontend.Web/wwwroot/css/site.css

Fixes #945 
Fjerner innsynsspesifikke tekster og felt.

Remove insight checks

---

Assessments.Frontend.Web/Infrastructure/Constants.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_GeographicVariationInCategory.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RegionalSpread.cshtml

liten forbokstav på kategori og svalbardvurderinger

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_CriteriaExplanation.cshtml

Fixes #820 
Fikser formatering på en del tall i kriterieforklaringen.

formatting some numbers

---

Assessments.Mapping/RedlistSpecies/Profiles/SpeciesAssessment2021ExportProfile.cs

closes #1143
legger til tomt tekstfelt på fylkesforekomst i eksporten på enkelte kategorier

Remove regionoccurrence on certain categories

---

Assessments.Data/Assessments.Data.csproj
Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
Assessments.Frontend.Web/Controllers/AlienSpeciesController.cs
Assessments.Mapping/Assessments.Mapping.csproj
Assessments.Tests/Assessments.Tests.csproj
Assessments.Transformation/Assessments.Transformation.csproj

Holde tritt med oppdaterte pakker

Oppdatere avhengigheter - nuget

---

Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/SpeciesAssessment2021.cshtml
Assessments.Frontend.Web/Views/Shared/_SidebarContent.cshtml
Assessments.Frontend.Web/wwwroot/css/site.css

Alltid vis info om status på forbudslista

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/StatisticsHelper.cs
Assessments.Frontend.Web/Models/AlienSpeciesListViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Graphs.cshtml
Assessments.Frontend.Web/wwwroot/css/graphs.css

Fixes #1175 
Legger også til at for den lille spredningsveierfiguren filtreres det nå på IntroductionSpread == "Introduction

Figur spreadningsveier detaljert

---

Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Graphs.cshtml

fikse bug i figur på rødlista

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/StatisticsHelper.cs
Assessments.Frontend.Web/Infrastructure/Constants.cs
Assessments.Frontend.Web/Models/AlienSpeciesListViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_BarChartHorizontal.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Graphs.cshtml
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/graphs.css
Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023IntroductionPathway.cs

Fixes #1163 
Fixes #1194 (sånn i samme slengen)
Fixes #1173 
Fixes #1175

Figur - spredningsveier

---

Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/Shared/_AssessmentPageHeader.cshtml
Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciecAssessment2023AlienSpeciesCategory.cs
Assessments.Mapping/AlienSpecies/Source/FA4Vurdering.cs
Assessments.Transformation/TransformAlienSpecies.cs

Fixes #1225 
Fixes #1184 
Fixes #960

Vurdert sammen

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RiskMatrix.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/_Layout.cshtml
Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
Assessments.Frontend.Web/Views/Shared/_AssessmentPageHeader.cshtml
Assessments.Frontend.Web/Views/Shared/_Layout.cshtml
Assessments.Frontend.Web/Views/Shared/_SpeciesGroup.cshtml
Assessments.Frontend.Web/wwwroot/css/alienSpecies.css
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/categorybar.css
Assessments.Frontend.Web/wwwroot/css/graphs.css
Assessments.Frontend.Web/wwwroot/css/listview.css
Assessments.Frontend.Web/wwwroot/css/riskMatrix.css
Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/css/site.css
Assessments.Frontend.Web/wwwroot/css/toggleSwitch.css

change order of texts

---

Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_RegionalSpread.cshtml
Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023.cs
Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs

explain occurrence area in regional spread

---

Assessments.Mapping/AlienSpecies/Helpers/AlienSpeciesAssessment2023ExportProfileHelper.cs
Assessments.Mapping/AlienSpecies/Model/AlienSpeciesAssessment2023Export.cs
Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023ExportProfile.cs

fix #1262 (se issue for detaljer).

Eksporten - justeringer. 

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterItemHelpers.cs
Assessments.Frontend.Web/Views/Shared/_ListView.cshtml
Assessments.Frontend.Web/Views/Shared/_SpeciesGroup.cshtml
Assessments.Frontend.Web/wwwroot/css/listview.css

change some icons for species groups

---

Assessments.Frontend.Web/Infrastructure/Constants.cs
Assessments.Frontend.Web/Infrastructure/Enums/AssessmentType.cs
Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesIndex.cshtml
Assessments.Frontend.Web/Views/Shared/_PageMenu.cshtml
Assessments.Frontend.Web/wwwroot/css/alienSpecies.css
Assessments.Frontend.Web/wwwroot/css/site.css

Legger til sidemeny slik at den ser noket lik ut som på hjemmesiden.

Sidemeny plan A

---

Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/Shared/_Links.cshtml
Assessments.Frontend.Web/Views/Shared/_SidebarContent.cshtml

Fjerne død link og element om forskrift for enkelte slekter

---

Assessments.Frontend.Web/Views/Shared/_PageTopBar.cshtml
Assessments.Frontend.Web/wwwroot/css/alienSpecies.css
Assessments.Frontend.Web/wwwroot/css/assessment.css
Assessments.Frontend.Web/wwwroot/css/buttons-and-chips.css
Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/graphs.css
Assessments.Frontend.Web/wwwroot/css/listview.css
Assessments.Frontend.Web/wwwroot/css/search.css
Assessments.Frontend.Web/wwwroot/css/site.css

Implementerer det meste av grafisk profil unntatt headeren.

Newprofile

---

Assessments.Frontend.Web/wwwroot/css/alienSpecies.css
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/buttons-and-chips.css

change some colors

---

Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/site.css

last minute fixes

---

Assessments.Frontend.Web/wwwroot/css/assessment.css

remove white from table background

---

Assessments.Frontend.Web/Controllers/AlienSpeciesController.cs
Assessments.Frontend.Web/Controllers/RedlistController.cs

Legger artskartsøket i søkeforslag inni en try/catch for både rødlista og fremmedartslista

put artskart search inside try/catch

---

Assessments.Frontend.Web/wwwroot/css/filter.css
Assessments.Frontend.Web/wwwroot/css/listview.css

Ting lå oppå hverandre.
Det gjør de ikke mer.

Oppgradering av wrap-punkter for listevisning

---

Assessments.Frontend.Web/Models/AlienSpeciesDetailViewModel.cs
Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_KnowMore.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_SpreadWays.cshtml
Assessments.Frontend.Web/Views/Shared/_SidebarContent.cshtml

Fixes #1305 
Fixes #1259 i samme slengen

hide regulation in sidebar for a few more species

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Search.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Search.cshtml
Assessments.Frontend.Web/wwwroot/css/search.css

adds a label and explanatory text to search field

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/ListPartials/_Filters.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/List/partials/_Filters.cshtml

Viser treff for

---

.github/workflows/develop.yml
.github/workflows/main.yml
.github/workflows/test.yml
Assessments.Data/Assessments.Data.csproj
Assessments.Frontend.Web/Assessments.Frontend.Web.csproj
Assessments.Frontend.Web/Dockerfile
Assessments.Mapping/Assessments.Mapping.csproj
Assessments.Shared/Assessments.Shared.csproj
Assessments.Tests/Assessments.Tests.csproj
Assessments.Transformation/Assessments.Transformation.csproj

formål - unngå å havne langt bak på bl.a. nuget pakker o.l.

oppdatert til .net 7 uten å ta i bruk nye features - kun referanser

---

Assessments.Frontend.Web/Views/Shared/_SidebarContent.cshtml

Improvement to banned list sentence

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_KnowMore.cshtml

Bugfix: html-formatering

---

Assessments.Frontend.Web/Models/PartialViewModels.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/Redlist/Species/2021/Assessment/SpeciesAssessment2021.cshtml
Assessments.Frontend.Web/Views/Shared/_CategoryDescription.cshtml
Assessments.Frontend.Web/Views/Shared/_ListView.cshtml
Assessments.Frontend.Web/wwwroot/css/bnw.css
Assessments.Frontend.Web/wwwroot/css/categorybar.css
Assessments.Frontend.Web/wwwroot/css/listview.css

Fixes #1368 
Fremmedartslista ble slik: 
Rødlista ble slik:
Kategorien til rødlista er nå reversert i helhold til ny profil, samt oppdatert med de nye fargene.

Oppdatering av visningen av kategoribaren

---

Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
Assessments.Frontend.Web/wwwroot/js/speciesImages.js
README.md

Fixes #1374
https://assessments-fe-dev.test.artsdatabanken.no/fremmedartslista/2023/641
Legger også til bilder av arter for rødlista: https://assessments-fe-dev.test.artsdatabanken.no/rodlisteforarter/2021/1381

Missing images

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/FilterItemHelpers.cs
Assessments.Frontend.Web/Infrastructure/Helpers.cs
Assessments.Frontend.Web/Infrastructure/RedlistSpecies/FilterItemHelpers.cs
Assessments.Frontend.Web/Views/AlienSpecies/2023/AssessmentPartials/_KnowMore.cshtml
Assessments.Mapping/AlienSpecies/Model/Enums/AlienSpeciesAssessment2023SpeciesStatus.cs
Assessments.Mapping/AlienSpecies/Profiles/AlienSpeciesAssessment2023Profile.cs

- Fikser en bug i fremmedartslistefilteret hvor et filter aktiverte et annet. 
- Endrer navn tilbake til laver fra larver i filter for rødlista.

Bug fix - filter

---

Assessments.Frontend.Web/Infrastructure/AlienSpecies/QueryHelpers.cs

remove duplicate species groups

---

Assessments.Frontend.Web/Views/AlienSpecies/2023/AlienSpeciesDetail.cshtml
Assessments.Frontend.Web/Views/AlienSpecies/_Layout.cshtml
Assessments.Frontend.Web/Views/Redlist/_Layout.cshtml
Assessments.Frontend.Web/Views/Shared/_Layout.cshtml
Assessments.Frontend.Web/wwwroot/js/cookies.js
Assessments.Frontend.Web/wwwroot/js/themes.js

Kommer ikke til å virke lokalt - må ut på kjent domenenavn for cookieinformation
Kan nå testes på https://beta.artsdatabanken.no/lister/rodlisteforarter/2021

Fix #1450 erstatte med CookieInformation løsning

---

Assessments.Mapping/RedlistSpecies/Helpers/SpeciesAssessment2021ProfileHelper.cs
Assessments.Mapping/RedlistSpecies/Profiles/SpeciesAssessment2021Profile.cs
Assessments.Mapping/RedlistSpecies/SpeciesAssessment2021.cs

ScientificNameHtml
